export const homes = [
  {
    id: 0,
    img: "src/assets/img/house-1.jpeg",
    alt: "House 1",
    heading: "Beautiful Family House",
    location: "USA",
    rooms: "5 rooms",
    size: "325 m²",
    price: "$1,200,000",
  },
  {
    id: 1,
    img: "src/assets/img/house-2.jpeg",
    alt: "House 2",
    heading: "Modern Glass Villa",
    location: "Canada",
    rooms: "6 rooms",
    size: "450 m²",
    price: "$2,750,000",
  },
  {
    id: 2,
    img: "src/assets/img/house-3.jpeg",
    alt: "House 3",
    heading: "Cozy Country House",
    location: "UK",
    rooms: "4 rooms",
    size: "250 m²",
    price: "$850,000",
  },
  {
    id: 3,
    img: "src/assets/img/house-4.jpeg",
    alt: "House 4",
    heading: "Large Rustic Villa",
    location: "Portugal",
    rooms: "6 rooms",
    size: "480 m²",
    price: "$1,950,000",
  },
  {
    id: 4,
    img: "src/assets/img/house-5.jpeg",
    alt: "House 5",
    heading: "Majestic Palace House",
    location: "Germany",
    rooms: "18 rooms",
    size: "4230 m²",
    price: "$9,500,000",
  },
  {
    id: 5,
    img: "src/assets/img/house-6.jpeg",
    alt: "House 6",
    heading: "Modern Family Apartment",
    location: "Italy",
    rooms: "3 rooms",
    size: "180 m²",
    price: "$600,000",
  },
];
