export const galleryImgs = [
  {
    id: self.crypto.randomUUID(),
    src: `/gal-1.jpeg`,
    alt: `Gallery image 1`,
    figureClassName: "gallery__item gallery__item--1",
  },
  {
    id: self.crypto.randomUUID(),
    src: `/gal-2.jpeg`,
    alt: `Gallery image 2`,
    figureClassName: "gallery__item gallery__item--2",
  },
  {
    id: self.crypto.randomUUID(),
    src: `/gal-3.jpeg`,
    alt: `Gallery image 3`,
    figureClassName: "gallery__item gallery__item--3",
  },
  {
    id: self.crypto.randomUUID(),
    src: `/gal-4.jpeg`,
    alt: `Gallery image 4`,
    figureClassName: "gallery__item gallery__item--4",
  },
  {
    id: self.crypto.randomUUID(),
    src: `/gal-5.jpeg`,
    alt: `Gallery image 5`,
    figureClassName: "gallery__item gallery__item--5",
  },
  {
    id: self.crypto.randomUUID(),
    src: `/gal-6.jpeg`,
    alt: `Gallery image 6`,
    figureClassName: "gallery__item gallery__item--6",
  },
  {
    id: self.crypto.randomUUID(),
    src: `/gal-7.jpeg`,
    alt: `Gallery image 7`,
    figureClassName: "gallery__item gallery__item--7",
  },
  {
    id: self.crypto.randomUUID(),
    src: `/gal-8.jpeg`,
    alt: `Gallery image 8`,
    figureClassName: "gallery__item gallery__item--8",
  },
  {
    id: self.crypto.randomUUID(),
    src: `/gal-9.jpeg`,
    alt: `Gallery image 9`,
    figureClassName: "gallery__item gallery__item--9",
  },
  {
    id: self.crypto.randomUUID(),
    src: `/gal-10.jpeg`,
    alt: `Gallery image 10`,
    figureClassName: "gallery__item gallery__item--10",
  },
  {
    id: self.crypto.randomUUID(),
    src: `/gal-11.jpeg`,
    alt: `Gallery image 11`,
    figureClassName: "gallery__item gallery__item--11",
  },
  {
    id: self.crypto.randomUUID(),
    src: `/gal-12.jpeg`,
    alt: `Gallery image 12`,
    figureClassName: "gallery__item gallery__item--12",
  },
  {
    id: self.crypto.randomUUID(),
    src: `/gal-13.jpeg`,
    alt: `Gallery image 13`,
    figureClassName: "gallery__item gallery__item--13",
  },
  {
    id: self.crypto.randomUUID(),
    src: `/gal-14.jpeg`,
    alt: `Gallery image 14`,
    figureClassName: "gallery__item gallery__item--14",
  },
];
